services:
  - type: web
    name: spit-finance-portal
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_CONFIG
        value: production
      - key: AUTO_SEED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.4"
